booktitle: "ä¸€å£ğ•"                               # æœ¬ã®ã‚¿ã‚¤ãƒˆãƒ«
aut: [ "SIGCOWW" ]                               # è‘—è€…ãƒªã‚¹ãƒˆ (EPUBã§ä½¿ã‚ã‚Œã‚‹)
date: "2023-08-13"                               # ç™ºè¡Œæ—¥
prt: "ã‚¢ã‚¯ã‚»ã‚¢"                                  # å°åˆ·æ‰€
pbl: "SIGCOWW"                                   # ç™ºè¡Œè€…
oth: "https://sigcoww.org/"                      # Webã‚µã‚¤ãƒˆ çœç•¥å¯
edt: "sigcoww@sigcoww.org"                       # é€£çµ¡å…ˆ çœç•¥å¯
feedback: "https://sigcoww.org/book/kmm/"        # é€£çµ¡ãƒ•ã‚©ãƒ¼ãƒ  çœç•¥å¯
#msg: "https://sigcoww.org/ ã§æ—¢åˆŠç´¹ä»‹ä¸­"        # ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ çœç•¥å¯

container_version: "kancolle"                    # desk ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ çœç•¥å¯
#layout_hash: "29c145e8f139ac90a42b623f8c52f37f" # layout.tex.erb ã®MD5ãƒãƒƒã‚·ãƒ¥ çœç•¥å¯
#sty_hash: "c202f8f4271d4302373d63acabe651b2"    # sigcoww.sty ã®MD5ãƒãƒƒã‚·ãƒ¥ çœç•¥å¯
#titlelatex: '\sigcowwpage'                      # æ‰‰ãƒšãƒ¼ã‚¸ çœç•¥å¯
download: "https://sigcoww.org/book/x/?key=%s"   # ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã‚³ãƒ¼ãƒ‰ç”¨æ–‡å­—åˆ— çœç•¥å¯
tallymark: false                                 # ãƒšãƒ¼ã‚¸æ•°ã‚’æ­£ã®å­—ã§è¡¨ç¾ã™ã‚‹ çœç•¥å¯

debug: true
language: ja
review_version: 2.0
bookname: book
stylesheet: [ "style.css" ]
epubversion: 3
htmlversion: 5
toclevel: 1
secnolevel: 2
toc: true
coverimage: epub-cover.png
titlepage: null
colophon: true
page_metric: B5
direction: "ltr"
opf_prefix: {
  ebpaj: "http://www.ebpaj.jp/",
  ibooks: "http://vocabulary.itunes.apple.com/rdf/ibooks/vocabulary-extensions-1.0/"
}
opf_meta: {"ebpaj:guide-version": "1.1.3", "ibooks:binding": "false"}
epubmaker:
  #mathml: true
  imgmath: true
  htmlext: xhtml
  #verify_target_images: true
  #force_include_images: []
  rename_for_legacy: true
  cover_linear: true
texstyle: sigcoww
texdocumentclass: ["jsbook", "uplatex,b5j,9pt,12Q,twoside,openany"]
dvioptions: "-d 5"
pdfmaker:
  hook_beforetexcompile: "./reviewhook.rb"
  image_scale2width: true
